[package]
name = "xpljn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
sxd-xpath = "0.4.2"
sxd-document = "0.3.2"
jsonpath = "0.1.1"
serde_json = "1.0.68"
tempfile = "3.2.0"
